services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: rag-backend
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-}
      - AWS_REGION=${AWS_REGION:-us-east-1}
    volumes:
      - ./server:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - rag-network

  frontend:
    image: nginx:alpine
    container_name: rag-frontend
    ports:
      - "3000:80"
    volumes:
      - ./client:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge